language: python
python:
- "3.6"
branches:
  only:
    - travis
before_script:
- pip install -r requirements.txt
- sudo apt-get update
- sudo apt-get install -y spatialite-bin libspatialite5
- ls -lah /usr/lib/x86_64-linux-gnu/
script: python build_cryptids_database.py
