language: python
python:
- "3.6"
branches:
  only:
    - master
before_script:
- pip install -r requirements.txt
- pip install datasette
- npm install -g now
- sudo apt-get update
- sudo apt-get install -y spatialite-bin libspatialite5
script: python build_cryptids_database.py
after_script:
- datasette publish now cryptids.db --spatialite -m metadata.json --token=$NOW_TOKEN --name=cryptids
- now alias --token=$NOW_TOKEN
