language: python
python:
- "3.6"
branches:
  only:
    - travis
before_script:
- pip install -r requirements.txt
- sudo apt-get install -y spatialite-bin libsqlite3-mod-spatialite
script: python build_cryptids_database.py
